version: '3.9'
services:
  filebeat01:
    image: docker.elastic.co/beats/filebeat:$ELASTIC_VERSION
    container_name: $FIRST_CONTAINER
    user: root
    environment:
      - ELASTICSEARCH_HOST=$ELASTICSEARCH_HOST
      - KIBANA_HOST=$KIBANA_HOST
      - ELASTICSEARCH_USERNAME=$ELASTIC_USER
      - ELASTICSEARCH_PASSWORD=$ELASTIC_PASSWORD
      - CONTAINER_LOGS_DIR=$CONTAINER_LOGS_DIR/elk_logs/
      - SERVICE_NAME=$FIRST_CONTAINER_SERVICE_NAME
      - LOGS_TO_FILE=$LOGS_TO_FILE
      - ERROR_LEVEL=$ERROR_LEVEL
      - STAGE_NAME=$STAGE_NAME
    configs:
      - source: first_container_config
        target: /usr/share/filebeat/filebeat.yml  
    volumes:
      - $ROOT_PATH/$FIRST_CONTAINER_LOGS:$CONTAINER_LOGS_DIR

    command: ["--strict.perms=false", "-system.hostfs=/hostfs"]
    networks:
      - beats

  filebeat02:
    image: docker.elastic.co/beats/filebeat:$ELASTIC_VERSION
    container_name: $SECOND_CONTAINER
    user: root
    environment:
      - ELASTICSEARCH_HOST=$ELASTICSEARCH_HOST
      - KIBANA_HOST=$KIBANA_HOST
      - ELASTICSEARCH_USERNAME=$ELASTIC_USER
      - ELASTICSEARCH_PASSWORD=$ELASTIC_PASSWORD
      - CONTAINER_LOGS_DIR=$CONTAINER_LOGS_DIR/elk_logs/
      - SERVICE_NAME=$SECOND_CONTAINER_SERVICE_NAME
      - LOGS_TO_FILE=$LOGS_TO_FILE
      - ERROR_LEVEL=$ERROR_LEVEL
      - STAGE_NAME=$STAGE_NAME
    configs:
      - source: second_container_config
        target: /usr/share/filebeat/filebeat.yml  
    volumes:
      - $ROOT_PATH/$SECOND_CONTAINER_LOGS:$CONTAINER_LOGS_DIR

    command: ["--strict.perms=false", "-system.hostfs=/hostfs"]
    networks:
      - beats
      
  filebeat03:
    image: docker.elastic.co/beats/filebeat:$ELASTIC_VERSION
    container_name: $THIRD_CONTAINER
    user: root
    environment:
      - ELASTICSEARCH_HOST=$ELASTICSEARCH_HOST
      - KIBANA_HOST=$KIBANA_HOST
      - ELASTICSEARCH_USERNAME=$ELASTIC_USER
      - ELASTICSEARCH_PASSWORD=$ELASTIC_PASSWORD
      - CONTAINER_LOGS_DIR=$CONTAINER_LOGS_DIR/elk_logs/
      - SERVICE_NAME=$THIRD_CONTAINER_SERVICE_NAME
      - LOGS_TO_FILE=$LOGS_TO_FILE
      - ERROR_LEVEL=$ERROR_LEVEL
      - STAGE_NAME=$STAGE_NAME
    configs:
      - source: third_container_config
        target: /usr/share/filebeat/filebeat.yml  
    volumes:
      - $ROOT_PATH/$THIRD_CONTAINER_LOGS:$CONTAINER_LOGS_DIR

    command: ["--strict.perms=false", "-system.hostfs=/hostfs"]
    networks:
      - beats
      
  filebeat04:
    image: docker.elastic.co/beats/filebeat:$ELASTIC_VERSION
    container_name: $FOURTH_CONTAINER
    user: root
    environment:
      - ELASTICSEARCH_HOST=$ELASTICSEARCH_HOST
      - KIBANA_HOST=$KIBANA_HOST
      - ELASTICSEARCH_USERNAME=$ELASTIC_USER
      - ELASTICSEARCH_PASSWORD=$ELASTIC_PASSWORD
      - CONTAINER_LOGS_DIR=$CONTAINER_LOGS_DIR/elk_logs/
      - SERVICE_NAME=$FOURTH_CONTAINER_SERVICE_NAME
      - LOGS_TO_FILE=$LOGS_TO_FILE
      - ERROR_LEVEL=$ERROR_LEVEL
      - STAGE_NAME=$STAGE_NAME
    configs:
      - source: fourth_container_config
        target: /usr/share/filebeat/filebeat.yml  
    volumes:
      - $ROOT_PATH/$FOURTH_CONTAINER_LOGS:$CONTAINER_LOGS_DIR

    command: ["--strict.perms=false", "-system.hostfs=/hostfs"]
    networks:
      - beats
      
  filebeat05:
    image: docker.elastic.co/beats/filebeat:$ELASTIC_VERSION
    container_name: $FIFTH_CONTAINER
    user: root
    environment:
      - ELASTICSEARCH_HOST=$ELASTICSEARCH_HOST
      - KIBANA_HOST=$KIBANA_HOST
      - ELASTICSEARCH_USERNAME=$ELASTIC_USER
      - ELASTICSEARCH_PASSWORD=$ELASTIC_PASSWORD
      - CONTAINER_LOGS_DIR=$CONTAINER_LOGS_DIR/elk_logs/
      - SERVICE_NAME=$FIFTH_CONTAINER_SERVICE_NAME
      - LOGS_TO_FILE=$LOGS_TO_FILE
      - ERROR_LEVEL=$ERROR_LEVEL
      - STAGE_NAME=$STAGE_NAME
    configs:
      - source: fifth_container_config
        target: /usr/share/filebeat/filebeat.yml  
    volumes:
      - $ROOT_PATH/$FIFTH_CONTAINER_LOGS:$CONTAINER_LOGS_DIR

    command: ["--strict.perms=false", "-system.hostfs=/hostfs"]
    networks:
      - beats
 
  filebeat06:
    image: docker.elastic.co/beats/filebeat:$ELASTIC_VERSION
    container_name: $SIXTH_CONTAINER
    user: root
    environment:
      - ELASTICSEARCH_HOST=$ELASTICSEARCH_HOST
      - KIBANA_HOST=$KIBANA_HOST
      - ELASTICSEARCH_USERNAME=$ELASTIC_USER
      - ELASTICSEARCH_PASSWORD=$ELASTIC_PASSWORD
      - CONTAINER_LOGS_DIR=$CONTAINER_LOGS_DIR/elk_logs/
      - SERVICE_NAME=$SIXTH_CONTAINER_SERVICE_NAME
      - LOGS_TO_FILE=$LOGS_TO_FILE
      - ERROR_LEVEL=$ERROR_LEVEL
      - STAGE_NAME=$STAGE_NAME
    configs:
      - source: sixth_container_config
        target: /usr/share/filebeat/filebeat.yml  
    volumes:
      - $ROOT_PATH/$SIXTH_CONTAINER_LOGS:$CONTAINER_LOGS_DIR

    command: ["--strict.perms=false", "-system.hostfs=/hostfs"]
    networks:
      - beats

  filebeat07:
    image: docker.elastic.co/beats/filebeat:$ELASTIC_VERSION
    container_name: $SEVENTH_CONTAINER
    user: root
    environment:
      - ELASTICSEARCH_HOST=$ELASTICSEARCH_HOST
      - KIBANA_HOST=$KIBANA_HOST
      - ELASTICSEARCH_USERNAME=$ELASTIC_USER
      - ELASTICSEARCH_PASSWORD=$ELASTIC_PASSWORD
      - CONTAINER_LOGS_DIR=$CONTAINER_LOGS_DIR/elk_logs/
      - SERVICE_NAME=$SEVENTH_CONTAINER_SERVICE_NAME
      - LOGS_TO_FILE=$LOGS_TO_FILE
      - ERROR_LEVEL=$ERROR_LEVEL
      - STAGE_NAME=$STAGE_NAME
    configs:
      - source: seventh_container_config
        target: /usr/share/filebeat/filebeat.yml  
    volumes:
      - $ROOT_PATH/$SEVENTH_CONTAINER_LOGS:$CONTAINER_LOGS_DIR

    command: ["--strict.perms=false", "-system.hostfs=/hostfs"]
    networks:
      - beats

  filebeat08:
    image: docker.elastic.co/beats/filebeat:$ELASTIC_VERSION
    container_name: $EIGHTH_CONTAINER
    user: root
    environment:
      - ELASTICSEARCH_HOST=$ELASTICSEARCH_HOST
      - KIBANA_HOST=$KIBANA_HOST
      - ELASTICSEARCH_USERNAME=$ELASTIC_USER
      - ELASTICSEARCH_PASSWORD=$ELASTIC_PASSWORD
      - CONTAINER_LOGS_DIR=$CONTAINER_LOGS_DIR/elk_logs/
      - SERVICE_NAME=$EIGHTH_CONTAINER_SERVICE_NAME
      - LOGS_TO_FILE=$LOGS_TO_FILE
      - ERROR_LEVEL=$ERROR_LEVEL
      - STAGE_NAME=$STAGE_NAME
    configs:
      - source: eighth_container_config
        target: /usr/share/filebeat/filebeat.yml  
    volumes:
      - $ROOT_PATH/$EIGHTH_CONTAINER_LOGS:$CONTAINER_LOGS_DIR

    command: ["--strict.perms=false", "-system.hostfs=/hostfs"]
    networks:
      - beats

  filebeat09:
    image: docker.elastic.co/beats/filebeat:$ELASTIC_VERSION
    container_name: $NINTH_CONTAINER
    user: root
    environment:
      - ELASTICSEARCH_HOST=$ELASTICSEARCH_HOST
      - KIBANA_HOST=$KIBANA_HOST
      - ELASTICSEARCH_USERNAME=$ELASTIC_USER
      - ELASTICSEARCH_PASSWORD=$ELASTIC_PASSWORD
      - CONTAINER_LOGS_DIR=$CONTAINER_LOGS_DIR/elk_logs/
      - SERVICE_NAME=$NINTH_CONTAINER_SERVICE_NAME
      - LOGS_TO_FILE=$LOGS_TO_FILE
      - ERROR_LEVEL=$ERROR_LEVEL
      - STAGE_NAME=$STAGE_NAME
    configs:
      - source: ninth_container_config
        target: /usr/share/filebeat/filebeat.yml  
    volumes:
      - $ROOT_PATH/$NINTH_CONTAINER_LOGS:$CONTAINER_LOGS_DIR

    command: ["--strict.perms=false", "-system.hostfs=/hostfs"]
    networks:
      - beats
 
  filebeat10:
    image: docker.elastic.co/beats/filebeat:$ELASTIC_VERSION
    container_name: $TENTH_CONTAINER
    user: root
    environment:
      - ELASTICSEARCH_HOST=$ELASTICSEARCH_HOST
      - KIBANA_HOST=$KIBANA_HOST
      - ELASTICSEARCH_USERNAME=$ELASTIC_USER
      - ELASTICSEARCH_PASSWORD=$ELASTIC_PASSWORD
      - CONTAINER_LOGS_DIR=$CONTAINER_LOGS_DIR/elk_logs/
      - SERVICE_NAME=$TENTH_CONTAINER_SERVICE_NAME
      - LOGS_TO_FILE=$LOGS_TO_FILE
      - ERROR_LEVEL=$ERROR_LEVEL
      - STAGE_NAME=$STAGE_NAME
    configs:
      - source: tenth_container_config
        target: /usr/share/filebeat/filebeat.yml  
    volumes:
      - $ROOT_PATH/$TENTH_CONTAINER_LOGS:$CONTAINER_LOGS_DIR

    command: ["--strict.perms=false", "-system.hostfs=/hostfs"]
    networks:
      - beats
      
  filebeat11:
    image: docker.elastic.co/beats/filebeat:$ELASTIC_VERSION
    container_name: $ELEVENTH_CONTAINER
    user: root
    environment:
      - ELASTICSEARCH_HOST=$ELASTICSEARCH_HOST
      - KIBANA_HOST=$KIBANA_HOST
      - ELASTICSEARCH_USERNAME=$ELASTIC_USER
      - ELASTICSEARCH_PASSWORD=$ELASTIC_PASSWORD
      - CONTAINER_LOGS_DIR=$CONTAINER_LOGS_DIR/elk_logs/
      - SERVICE_NAME=$ELEVENTH_CONTAINER_SERVICE_NAME
      - LOGS_TO_FILE=$LOGS_TO_FILE
      - ERROR_LEVEL=$ERROR_LEVEL
      - STAGE_NAME=$STAGE_NAME
    configs:
      - source: eleventh_container_config
        target: /usr/share/filebeat/filebeat.yml  
    volumes:
      - $ROOT_PATH/$ELEVENTH_CONTAINER_LOGS:$CONTAINER_LOGS_DIR

    command: ["--strict.perms=false", "-system.hostfs=/hostfs"]
    networks:
      - beats



configs:
  first_container_config:
    file: $ROOT_PATH/$FIRST_CONTAINER_CONFIG:/usr/share/filebeat/filebeat.yml
  second_container_config:
    file: $ROOT_PATH/$SECOND_CONTAINER_CONFIG:/usr/share/filebeat/filebeat.yml
  third_container_config:
    file: $ROOT_PATH/$THIRD_CONTAINER_CONFIG:/usr/share/filebeat/filebeat.yml
  fourth_container_config:
    file: $ROOT_PATH/$FOURTH_CONTAINER_CONFIG:/usr/share/filebeat/filebeat.yml
  fifth_container_config:
    file: $ROOT_PATH/$FIFTH_CONTAINER_CONFIG:/usr/share/filebeat/filebeat.yml
  sixth_container_config:
    file: $ROOT_PATH/$SIXTH_CONTAINER_CONFIG:/usr/share/filebeat/filebeat.yml
  seventh_container_config:
    file: $ROOT_PATH/$SEVENTH_CONTAINER_CONFIG:/usr/share/filebeat/filebeat.yml
  eighth_container_config:
    file: $ROOT_PATH/$EIGHTH_CONTAINER_CONFIG:/usr/share/filebeat/filebeat.yml
  ninth_container_config:
    file: $ROOT_PATH/$NINTH_CONTAINER_CONFIG:/usr/share/filebeat/filebeat.yml
  tenth_container_config:
    file: $ROOT_PATH/$TENTH_CONTAINER_CONFIG:/usr/share/filebeat/filebeat.yml
  eleventh_container_config:
    file: $ROOT_PATH/$ELEVENTH_CONTAINER_CONFIG:/usr/share/filebeat/filebeat.yml	 

	  
networks:
  beats:
    external: true
    name: bridge