version: '3.9'
services:
  filebeat01:
    image: docker.elastic.co/beats/filebeat:$ELASTIC_VERSION
    container_name: $FIRST_CONTAINER
    user: root
    environment:
      - ELASTICSEARCH_HOST=$ELASTICSEARCH_HOST
      - KIBANA_HOST=$KIBANA_HOST
      - ELASTICSEARCH_USERNAME=$ELASTIC_USER
      - ELASTICSEARCH_PASSWORD=$ELASTIC_PASSWORD
      - CONTAINER_LOGS_DIR=$CONTAINER_LOGS_DIR/elk_logs/
      - SERVICE_NAME=$FIRST_CONTAINER_SERVICE_NAME
      - LOGS_TO_FILE=$LOGS_TO_FILE
      - ERROR_LEVEL=$ERROR_LEVEL
      - STAGE_NAME=$STAGE_NAME
    volumes:
        - type: bind
          source: $ROOT_PATH/$FIRST_CONTAINER_CONFIG
          target: /usr/share/filebeat/filebeat.yml
        - type: bind
          source: $ROOT_PATH/$FIRST_CONTAINER_LOGS
          target: $CONTAINER_LOGS_DIR
          read_only: true
    command: ["--strict.perms=false"]
    networks:
      - beats

  filebeat02:
    image: docker.elastic.co/beats/filebeat:$ELASTIC_VERSION
    container_name: $SECOND_CONTAINER
    user: root
    environment:
      - ELASTICSEARCH_HOST=$ELASTICSEARCH_HOST
      - KIBANA_HOST=$KIBANA_HOST
      - ELASTICSEARCH_USERNAME=$ELASTIC_USER
      - ELASTICSEARCH_PASSWORD=$ELASTIC_PASSWORD
      - CONTAINER_LOGS_DIR=$CONTAINER_LOGS_DIR/elk_logs/
      - SERVICE_NAME=$SECOND_CONTAINER_SERVICE_NAME
      - LOGS_TO_FILE=$LOGS_TO_FILE
      - ERROR_LEVEL=$ERROR_LEVEL
      - STAGE_NAME=$STAGE_NAME
    volumes:
        - type: bind
          source: $ROOT_PATH/$SECOND_CONTAINER_CONFIG
          target: /usr/share/filebeat/filebeat.yml
        - type: bind
          source: $ROOT_PATH/$SECOND_CONTAINER_LOGS
          target: $CONTAINER_LOGS_DIR
          read_only: true

    command: ["--strict.perms=false"]
    networks:
      - beats
      
  filebeat03:
    image: docker.elastic.co/beats/filebeat:$ELASTIC_VERSION
    container_name: $THIRD_CONTAINER
    user: root
    environment:
      - ELASTICSEARCH_HOST=$ELASTICSEARCH_HOST
      - KIBANA_HOST=$KIBANA_HOST
      - ELASTICSEARCH_USERNAME=$ELASTIC_USER
      - ELASTICSEARCH_PASSWORD=$ELASTIC_PASSWORD
      - CONTAINER_LOGS_DIR=$CONTAINER_LOGS_DIR/elk_logs/
      - SERVICE_NAME=$THIRD_CONTAINER_SERVICE_NAME
      - LOGS_TO_FILE=$LOGS_TO_FILE
      - ERROR_LEVEL=$ERROR_LEVEL
      - STAGE_NAME=$STAGE_NAME
    volumes:
        - type: bind
          source: $ROOT_PATH/$THIRD_CONTAINER_CONFIG
          target: /usr/share/filebeat/filebeat.yml
        - type: bind
          source: $ROOT_PATH/$THIRD_CONTAINER_LOGS
          target: $CONTAINER_LOGS_DIR
          read_only: true
          
    command: ["--strict.perms=false"]
    networks:
      - beats
      
  filebeat04:
    image: docker.elastic.co/beats/filebeat:$ELASTIC_VERSION
    container_name: $FOURTH_CONTAINER
    user: root
    environment:
      - ELASTICSEARCH_HOST=$ELASTICSEARCH_HOST
      - KIBANA_HOST=$KIBANA_HOST
      - ELASTICSEARCH_USERNAME=$ELASTIC_USER
      - ELASTICSEARCH_PASSWORD=$ELASTIC_PASSWORD
      - CONTAINER_LOGS_DIR=$CONTAINER_LOGS_DIR/elk_logs/
      - SERVICE_NAME=$FOURTH_CONTAINER_SERVICE_NAME
      - LOGS_TO_FILE=$LOGS_TO_FILE
      - ERROR_LEVEL=$ERROR_LEVEL
      - STAGE_NAME=$STAGE_NAME
    volumes:
        - type: bind
          source: $ROOT_PATH/$FOURTH_CONTAINER_CONFIG
          target: /usr/share/filebeat/filebeat.yml
        - type: bind
          source: $ROOT_PATH/$FOURTH_CONTAINER_LOGS
          target: $CONTAINER_LOGS_DIR
          read_only: true
          

    command: ["--strict.perms=false"]
    networks:
      - beats
      
  filebeat05:
    image: docker.elastic.co/beats/filebeat:$ELASTIC_VERSION
    container_name: $FIFTH_CONTAINER
    user: root
    environment:
      - ELASTICSEARCH_HOST=$ELASTICSEARCH_HOST
      - KIBANA_HOST=$KIBANA_HOST
      - ELASTICSEARCH_USERNAME=$ELASTIC_USER
      - ELASTICSEARCH_PASSWORD=$ELASTIC_PASSWORD
      - CONTAINER_LOGS_DIR=$CONTAINER_LOGS_DIR/elk_logs/
      - SERVICE_NAME=$FIFTH_CONTAINER_SERVICE_NAME
      - LOGS_TO_FILE=$LOGS_TO_FILE
      - ERROR_LEVEL=$ERROR_LEVEL
      - STAGE_NAME=$STAGE_NAME
    volumes:
        - type: bind
          source: $ROOT_PATH/$FIFTH_CONTAINER_CONFIG
          target: /usr/share/filebeat/filebeat.yml
        - type: bind
          source: $ROOT_PATH/$FIFTH_CONTAINER_LOGS
          target: $CONTAINER_LOGS_DIR
          read_only: true
          
    command: ["--strict.perms=false"]
    networks:
      - beats
 
  filebeat06:
    image: docker.elastic.co/beats/filebeat:$ELASTIC_VERSION
    container_name: $SIXTH_CONTAINER
    user: root
    environment:
      - ELASTICSEARCH_HOST=$ELASTICSEARCH_HOST
      - KIBANA_HOST=$KIBANA_HOST
      - ELASTICSEARCH_USERNAME=$ELASTIC_USER
      - ELASTICSEARCH_PASSWORD=$ELASTIC_PASSWORD
      - CONTAINER_LOGS_DIR=$CONTAINER_LOGS_DIR/elk_logs/
      - SERVICE_NAME=$SIXTH_CONTAINER_SERVICE_NAME
      - LOGS_TO_FILE=$LOGS_TO_FILE
      - ERROR_LEVEL=$ERROR_LEVEL
      - STAGE_NAME=$STAGE_NAME
    volumes:
        - type: bind
          source: $ROOT_PATH/$SIXTH_CONTAINER_CONFIG
          target: /usr/share/filebeat/filebeat.yml
        - type: bind
          source: $ROOT_PATH/$SIXTH_CONTAINER_LOGS
          target: $CONTAINER_LOGS_DIR
          read_only: true
          
    command: ["--strict.perms=false"]
    networks:
      - beats

  filebeat07:
    image: docker.elastic.co/beats/filebeat:$ELASTIC_VERSION
    container_name: $SEVENTH_CONTAINER
    user: root
    environment:
      - ELASTICSEARCH_HOST=$ELASTICSEARCH_HOST
      - KIBANA_HOST=$KIBANA_HOST
      - ELASTICSEARCH_USERNAME=$ELASTIC_USER
      - ELASTICSEARCH_PASSWORD=$ELASTIC_PASSWORD
      - CONTAINER_LOGS_DIR=$CONTAINER_LOGS_DIR/elk_logs/
      - SERVICE_NAME=$SEVENTH_CONTAINER_SERVICE_NAME
      - LOGS_TO_FILE=$LOGS_TO_FILE
      - ERROR_LEVEL=$ERROR_LEVEL
      - STAGE_NAME=$STAGE_NAME
    volumes:
        - type: bind
          source: $ROOT_PATH/$SEVENTH_CONTAINER_CONFIG
          target: /usr/share/filebeat/filebeat.yml
        - type: bind
          source: $ROOT_PATH/$SEVENTH_CONTAINER_LOGS
          target: $CONTAINER_LOGS_DIR
          read_only: true
          
    command: ["--strict.perms=false"]
    networks:
      - beats

  filebeat08:
    image: docker.elastic.co/beats/filebeat:$ELASTIC_VERSION
    container_name: $EIGHTH_CONTAINER
    user: root
    environment:
      - ELASTICSEARCH_HOST=$ELASTICSEARCH_HOST
      - KIBANA_HOST=$KIBANA_HOST
      - ELASTICSEARCH_USERNAME=$ELASTIC_USER
      - ELASTICSEARCH_PASSWORD=$ELASTIC_PASSWORD
      - CONTAINER_LOGS_DIR=$CONTAINER_LOGS_DIR/elk_logs/
      - SERVICE_NAME=$EIGHTH_CONTAINER_SERVICE_NAME
      - LOGS_TO_FILE=$LOGS_TO_FILE
      - ERROR_LEVEL=$ERROR_LEVEL
      - STAGE_NAME=$STAGE_NAME
    volumes:
        - type: bind
          source: $ROOT_PATH/$EIGHTH_CONTAINER_CONFIG
          target: /usr/share/filebeat/filebeat.yml
        - type: bind
          source: $ROOT_PATH/$EIGHTH_CONTAINER_LOGS
          target: $CONTAINER_LOGS_DIR
          read_only: true
          
    command: ["--strict.perms=false"]
    networks:
      - beats

  filebeat09:
    image: docker.elastic.co/beats/filebeat:$ELASTIC_VERSION
    container_name: $NINTH_CONTAINER
    user: root
    environment:
      - ELASTICSEARCH_HOST=$ELASTICSEARCH_HOST
      - KIBANA_HOST=$KIBANA_HOST
      - ELASTICSEARCH_USERNAME=$ELASTIC_USER
      - ELASTICSEARCH_PASSWORD=$ELASTIC_PASSWORD
      - CONTAINER_LOGS_DIR=$CONTAINER_LOGS_DIR/elk_logs/
      - SERVICE_NAME=$NINTH_CONTAINER_SERVICE_NAME
      - LOGS_TO_FILE=$LOGS_TO_FILE
      - ERROR_LEVEL=$ERROR_LEVEL
      - STAGE_NAME=$STAGE_NAME
    volumes:
        - type: bind
          source: $ROOT_PATH/$NINTH_CONTAINER_CONFIG
          target: /usr/share/filebeat/filebeat.yml
        - type: bind
          source: $ROOT_PATH/$NINTH_CONTAINER_LOGS
          target: $CONTAINER_LOGS_DIR
          read_only: true
          
    command: ["--strict.perms=false"]
    networks:
      - beats
 
  filebeat10:
    image: docker.elastic.co/beats/filebeat:$ELASTIC_VERSION
    container_name: $TENTH_CONTAINER
    user: root
    environment:
      - ELASTICSEARCH_HOST=$ELASTICSEARCH_HOST
      - KIBANA_HOST=$KIBANA_HOST
      - ELASTICSEARCH_USERNAME=$ELASTIC_USER
      - ELASTICSEARCH_PASSWORD=$ELASTIC_PASSWORD
      - CONTAINER_LOGS_DIR=$CONTAINER_LOGS_DIR/elk_logs/
      - SERVICE_NAME=$TENTH_CONTAINER_SERVICE_NAME
      - LOGS_TO_FILE=$LOGS_TO_FILE
      - ERROR_LEVEL=$ERROR_LEVEL
      - STAGE_NAME=$STAGE_NAME
    volumes:
        - type: bind
          source: $ROOT_PATH/$TENTH_CONTAINER_CONFIG
          target: /usr/share/filebeat/filebeat.yml
        - type: bind
          source: $ROOT_PATH/$TENTH_CONTAINER_LOGS
          target: $CONTAINER_LOGS_DIR
          read_only: true
          
    command: ["--strict.perms=false"]
    networks:
      - beats
      
  filebeat11:
    image: docker.elastic.co/beats/filebeat:$ELASTIC_VERSION
    container_name: $ELEVENTH_CONTAINER
    user: root
    environment:
      - ELASTICSEARCH_HOST=$ELASTICSEARCH_HOST
      - KIBANA_HOST=$KIBANA_HOST
      - ELASTICSEARCH_USERNAME=$ELASTIC_USER
      - ELASTICSEARCH_PASSWORD=$ELASTIC_PASSWORD
      - CONTAINER_LOGS_DIR=$CONTAINER_LOGS_DIR/elk_logs/
      - SERVICE_NAME=$ELEVENTH_CONTAINER_SERVICE_NAME
      - LOGS_TO_FILE=$LOGS_TO_FILE
      - ERROR_LEVEL=$ERROR_LEVEL
      - STAGE_NAME=$STAGE_NAME
    volumes:
        - type: bind
          source: $ROOT_PATH/$ELEVENTH_CONTAINER_CONFIG
          target: /usr/share/filebeat/filebeat.yml
        - type: bind
          source: $ROOT_PATH/$ELEVENTH_CONTAINER_LOGS
          target: $CONTAINER_LOGS_DIR
          read_only: true
          
    command: ["--strict.perms=false"]
    networks:
      - beats

  metricbeat:
    image: docker.elastic.co/beats/metricbeat:$ELASTIC_VERSION
    container_name: $METRICS_CONTAINER
    user: root
    environment:
      - ELASTICSEARCH_HOST=$ELASTICSEARCH_HOST
      - KIBANA_HOST=$KIBANA_HOST
      - ELASTICSEARCH_USERNAME=$ELASTIC_USER
      - ELASTICSEARCH_PASSWORD=$ELASTIC_PASSWORD
      - LOGS_TO_FILE=$LOGS_TO_FILE
      - ERROR_LEVEL=$ERROR_LEVEL
      - STAGE_NAME=$STAGE_NAME
    volumes:
        - type: bind
          source: $ROOT_PATH/$HEARTBEAT_CONTAINER_CONFIG
          target: /usr/share/metricbeat/metricbeat.yml
          
        - type: bind
          source: /var/run/docker.sock
          target: /var/run/docker.sock
          read_only: true

        - type: bind
          source: /sys/fs/cgroup
          target: /hostfs/sys/fs/cgroup
          read_only: true
          
        - type: bind
          source: /proc
          target: /hostfs/proc
          read_only: true   
          
        - type: bind
          source: /
          target: /hostfs
          read_only: true

    command: ["--strict.perms=false", "-system.hostfs=/hostfs"]
    networks:
      - beats
      
  heartbeat:
    image: docker.elastic.co/beats/heartbeat:$ELASTIC_VERSION
    container_name: $HEARTBEAT_CONTAINER
    user: root
    environment:
      - ELASTICSEARCH_HOST=$ELASTICSEARCH_HOST
      - KIBANA_HOST=$KIBANA_HOST
      - ELASTICSEARCH_USERNAME=$ELASTIC_USER
      - ELASTICSEARCH_PASSWORD=$ELASTIC_PASSWORD
      - LOGS_TO_FILE=$LOGS_TO_FILE
      - ERROR_LEVEL=$ERROR_LEVEL
      - STAGE_NAME=$STAGE_NAME
    volumes:
        - type: bind
          source: $ROOT_PATH/$HEARTBEAT_CONTAINER_CONFIG
          target: /usr/share/heartbeat/heartbeat.yml

    command: ["--strict.perms=false"]
    networks:
      - beats
          
networks:
  beats:
    name: beats
    driver: bridge