version: '3.9'
services:
  heartbeat:
    image: docker.elastic.co/beats/heartbeat:$ELASTIC_VERSION
    container_name: $HEARTBEAT_CONTAINER
    user: root
    environment:
      - ELASTICSEARCH_HOST=$ELASTICSEARCH_HOST
      - KIBANA_HOST=$KIBANA_HOST
      - ELASTICSEARCH_USERNAME=$ELASTIC_USER
      - ELASTICSEARCH_PASSWORD=$ELASTIC_PASSWORD
      - STAGE_NAME=$STAGE_NAME
    volumes:
        - type: bind
          source: $ROOT_PATH/$METRICBEAT_CONTAINER_CONFIG
          target: /usr/share/metricbeat/metricbeat.yml
          read_only: true

    command: ["--strict.perms=false", "-system.hostfs=/hostfs"]
    networks:
      - beats
          
networks:
  beats:
    name: beats
    driver: bridge