version: '3.9'
services:
  metricbeat:
    image: docker.elastic.co/beats/metricbeat:$ELASTIC_VERSION
    container_name: $METRICS_CONTAINER
    user: root
    environment:
      - ELASTICSEARCH_HOST=$ELASTICSEARCH_HOST
      - KIBANA_HOST=$KIBANA_HOST
      - ELASTICSEARCH_USERNAME=$ELASTIC_USER
      - ELASTICSEARCH_PASSWORD=$ELASTIC_PASSWORD
      - STAGE_NAME=$STAGE_NAME
    volumes:
        - type: bind
          source: $ROOT_PATH/$HEARTBEAT_CONTAINER_CONFIG
          target: /usr/share/metricbeat/metricbeat.yml
          read_only: true
          
        - type: bind
          source: /var/run/docker.sock
          target: /var/run/docker.sock
          read_only: true

        - type: bind
          source: /sys/fs/cgroup
          target: /hostfs/sys/fs/cgroup
          read_only: true
          
        - type: bind
          source: /proc
          target: /hostfs/proc
          read_only: true   
          
        - type: bind
          source: /
          target: /hostfs
          read_only: true

    command: ["--strict.perms=false", "-system.hostfs=/hostfs"]
    networks:
      - beats
     
networks:
  beats:
    name: beats
    driver: bridge